### ISSUE TITLE
stuck at "npm install" step

### ISSUE THREAD

**Issue by arut16** [kevincastejon/js-raspberrypi-piwebradio#2]
Hi Kevin,

First of all, thank you for this great project that I am bringing to fruition thanks to your work.
Unfortunately I'm stuck at the "npm install" step.
Error message below.

Can you help me please ? I waited for minutes but nothing happened. It stays stuck there. What to do ?

![image](https://github.com/kevincastejon/js-raspberrypi-piwebradio/assets/58274805/537c82d9-b372-44f5-851d-f07c966e0751)

**Comment by kevincastejon** [comment]
hi @arut16 thanks for your words!
It's been a while I haven't check this project, I know a lot of changes happened in NodeJS since..
I'll try to follow the whole process and address issues ASAP, I got some free time these days, I'll let you know on here.
Can you please provide more information about what you are using, as :
Which Raspberry board version?
Which Raspbian version?
Which nodejs version?
Which audio hat?

**Comment by arut16** [comment]
Bonjour @kevincastejon ,
Merci pour ton aide ! ;-)

**Which Raspberry board version?** Raspberry Pi Zero WH
**Which Raspbian version?** 
```
pi@PiWebRadio:~/.npm/_logs $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
**Which nodejs version?** 10.22.0
**Which audio hat?** WaveShare WM8960

Actually, since I opened this issue here I tried many things. In fact, the step where I thought I was stuck in the screenshot above ended up going after a good 20 minutes but not without errors...

```
pi@PiWebRadio:~/js-raspberrypi-piwebradio-webapp $ npm install

> raspberrypi-piwebradio-webapp@1.1.0 preinstall /home/pi/js-raspberrypi-piwebradio-webapp
> cd ./client/ && npm install && npm run build

npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

audited 1689 packages in 948.286s

65 packages are looking for funding
  run `npm fund` for details

found 407 vulnerabilities (5 low, 197 moderate, 164 high, 41 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> piwebradio-webapp-client@0.1.0 build /home/pi/js-raspberrypi-piwebradio-webapp/client
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Compiled successfully.

File sizes after gzip:

  288.07 KB  build/static/js/2.c0d9c25e.chunk.js
  59.35 KB   build/static/css/2.48db8b0f.chunk.css
  2.13 KB    build/static/js/main.f2effcc4.chunk.js
  785 B      build/static/js/runtime-main.f90e610a.js
  280 B      build/static/css/main.34de6062.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy


> raspberrypi-rotary-encoder@1.9.0 preinstall /home/pi/js-raspberrypi-piwebradio-webapp/node_modules/raspberrypi-rotary-encoder
> sudo apt-get install python-dev python-pip -y && sudo apt-get install wiringpi -y && sudo pip install wiringpi && cd && sudo rm -rf py-gaugette && git clone https://github.com/guyc/py-gaugette.git && cd py-gaugette && sudo python setup.py install && cd && sudo rm -rf py-spidev && git clone https://github.com/doceme/py-spidev.git && cd py-spidev && sudo python setup.py install

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate

> raspberrypi-piwebradio@1.25.0 preinstall /home/pi/js-raspberrypi-piwebradio-webapp/node_modules/raspberrypi-piwebradio
> sudo apt-get install mpg123 -y

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mpg123 is already the newest version (1.26.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! raspberrypi-rotary-encoder@1.9.0 preinstall: `sudo apt-get install python-dev python-pip -y && sudo apt-get install wiringpi -y && sudo pip install wiringpi && cd && sudo rm -rf py-gaugette && git clone https://github.com/guyc/py-gaugette.git && cd py-gaugette && sudo python setup.py install && cd && sudo rm -rf py-spidev && git clone https://github.com/doceme/py-spidev.git && cd py-spidev && sudo python setup.py install`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the raspberrypi-rotary-encoder@1.9.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2024-01-21T15_59_20_169Z-debug.log
```


At the end of this “npm install” step, the radio starts sometime as expected. I can add other radios on the web config page; I have not yet received the potentiometers for the volume and the radio change. I don't know yet if they will work as is. They are on the way from Ali...

The problem is that at the end of the process (pm2 installed and etc...), when restarting the raspberry, the screen remains off and no radio starts. Access to the http config page is no longer possible. With "pm2 monit, I have this:

![Capture d’écran 2024-01-21 203626](https://github.com/kevincastejon/js-raspberrypi-piwebradio/assets/58274805/77ed82ad-0bff-48dc-b0aa-42acd99eb392)

Here is the end log file mentioned at the end:

```
pi@PiWebRadio:~/.npm/_logs $ sudo nano 2024-01-21T16_57_50_436Z-debug.log
  GNU nano 5.4                                                                                          2024-01-21T16_57_50_436Z-debug.log *
244 silly saveTree │ │ │ └── unpipe@1.0.0
244 silly saveTree │ │ └─┬ type-is@1.6.18
244 silly saveTree │ │   └── media-typer@0.3.0
244 silly saveTree │ ├── content-disposition@0.5.2
244 silly saveTree │ ├── content-type@1.0.5
244 silly saveTree │ ├── cookie-signature@1.0.6
244 silly saveTree │ ├── cookie@0.3.1
244 silly saveTree │ ├── debug@2.6.9
244 silly saveTree │ ├── depd@1.1.2
244 silly saveTree │ ├── encodeurl@1.0.2
244 silly saveTree │ ├── escape-html@1.0.3
244 silly saveTree │ ├── etag@1.8.1
244 silly saveTree │ ├─┬ finalhandler@1.1.1
244 silly saveTree │ │ └── parseurl@1.3.3
244 silly saveTree │ ├── fresh@0.5.2
244 silly saveTree │ ├── merge-descriptors@1.0.1
244 silly saveTree │ ├── methods@1.1.2
244 silly saveTree │ ├── on-finished@2.3.0
244 silly saveTree │ ├── parseurl@1.3.3
244 silly saveTree │ ├── path-to-regexp@0.1.7
244 silly saveTree │ ├─┬ proxy-addr@2.0.7
244 silly saveTree │ │ ├── forwarded@0.2.0
244 silly saveTree │ │ └── ipaddr.js@1.9.1
244 silly saveTree │ ├── qs@6.5.2
244 silly saveTree │ ├── range-parser@1.2.1
244 silly saveTree │ ├── safe-buffer@5.1.2
244 silly saveTree │ ├─┬ send@0.16.2
244 silly saveTree │ │ ├── destroy@1.0.4
244 silly saveTree │ │ └── mime@1.4.1
244 silly saveTree │ ├── serve-static@1.13.2
244 silly saveTree │ ├── setprototypeof@1.1.0
244 silly saveTree │ ├── statuses@1.4.0
244 silly saveTree │ ├── type-is@1.6.18
244 silly saveTree │ └── utils-merge@1.0.1
244 silly saveTree ├─┬ morgan@1.9.1
244 silly saveTree │ ├── basic-auth@2.0.1
244 silly saveTree │ └── on-headers@1.0.2
244 silly saveTree └── raspberrypi-rotary-encoder@1.9.0
245 verbose stack Error: raspberrypi-rotary-encoder@1.9.0 preinstall: `sudo apt-get install python-dev python-pip -y && sudo apt-get install wiringpi -y && sudo pip install wiringpi && cd && sudo rm -rf py-gaugette && git clone https://>
245 verbose stack Exit status 100
245 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
245 verbose stack     at EventEmitter.emit (events.js:198:13)
245 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
245 verbose stack     at ChildProcess.emit (events.js:198:13)
245 verbose stack     at maybeClose (internal/child_process.js:982:16)
245 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
246 verbose pkgid raspberrypi-rotary-encoder@1.9.0
247 verbose cwd /home/pi/js-raspberrypi-piwebradio-webapp
248 verbose Linux 6.1.21+
249 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "raspberrypi-rotary-encoder" "--unsafe-perm"
250 verbose node v10.22.0
251 verbose npm  v6.14.6
252 error code ELIFECYCLE
253 error errno 100
254 error raspberrypi-rotary-encoder@1.9.0 preinstall: `sudo apt-get install python-dev python-pip -y && sudo apt-get install wiringpi -y && sudo pip install wiringpi && cd && sudo rm -rf py-gaugette && git clone https://github.com/guyc>
254 error Exit status 100
255 error Failed at the raspberrypi-rotary-encoder@1.9.0 preinstall script.
255 error This is probably not a problem with npm. There is likely additional logging output above.
256 verbose exit [ 100, true ]

```
I hope this information will help you see things more clearly. Your project is too close to my heart to give up now. I've been spending my evenings there for 3 days trying to troubleshoot this problem, going through the forums and other IT articles but I obviously lack the skills that you certainly have...

Don't hesitate to ask me anything.

**Comment by kevincastejon** [comment]
There was an issue with my other repo rotary-encoders, i've just fixed it but now I have to update the fixed package to the piwebradio repo. Will do this tomorrow and let you about it

**Comment by arut16** [comment]
If I understand correctly, the installation issue of this repo is due to pip module witch is not supported (?)...

**Comment by kevincastejon** [comment]
the issue should be fixed with the latest commit, just be sure that the following directories ARE NOT PRESENT on the raspi (as previous failed installs may have let garbage behind)
- WiringPi
- py-gaugette
- py-spidev

Just delete them if they are here and restart the install process

**Comment by arut16** [comment]
Perfect ! It works !  Have to test potentiometers but at least radio starts again after a reboot. 

Thank you very much Kevin !
